{
 "title": "Snackquest",
 "tags": [
  "snackquest",
  "flask",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"snackquest-backend\"}"
    }
   ]
  },
  {
   "title": "Request Count by Method",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (rate(snackquest_request_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Total Request Time per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(snackquest_request_time_sum[1m])"
    }
   ]
  },
  {
   "title": "Requests per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(snackquest_request_count_total[1m])"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(snackquest_request_latency_sum[1m]) / rate(snackquest_request_latency_count[1m])"
    }
   ]
  },
  {
   "title": "Total Error Count (4xx/5xx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(snackquest_request_count_total{status=~\"4..|5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request Count by Status Code",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(snackquest_request_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Error Rate (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(snackquest_request_count_total{status=~\"4..|5..\"}[5m])) / sum(rate(snackquest_request_count_total[5m]))"
    }
   ]
  }
 ]
}