---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: snackquest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: snackquest-repo
  policy:
    alphabetical:
      order: asc
