name: "[DEV] Build and Push"
run-name: "[DEV] Build and Push: ${{ github.sha }}"

on:
  push:
    branches:
      - dev

jobs:
  gather-informations:
    runs-on: ubuntu-latest
    outputs:
      build_time: ${{ steps.date.outputs.date }}
    steps:
      - id: date
        name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  build-and-push:
    needs:
      - gather-informations
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: axelnemes/snackquest-dev:${{ needs.gather-informations.outputs.build_time }}-${{ github.sha }}, axelnemes/snackquest-dev:latest
          platforms: linux/arm64, linux/amd64
