name: "[PROD] Build and Push"
run-name: "[PROD] Build and Push: ${{ github.sha }}"

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
    paths:
      - 'snackquest/**'
      - 'web/**'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  gather-informations:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      build_time: ${{ steps.date.outputs.date }}
      build_environment: ${{ steps.environment.outputs.build_environment }}
    steps:
      - id: date
        name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  release:
    needs:
      - gather-informations
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Build snackquest binary
      run: make packages && make binary

    - uses: ncipollo/release-action@v1
      with:
        body: ${{ github.event.pull_request.body }}
        tag: snackquest-${{ needs.gather-informations.outputs.build_time }}-${{ github.sha }}
        artifacts: "dist/snackquest"

  docker:
    needs:
      - release
      - gather-informations
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: axelnemes/snackquest:${{ needs.gather-informations.outputs.build_time }}-${{ github.sha }}, axelnemes/snackquest:latest
          platforms: linux/arm64, linux/amd64
